name: base58check
description: Base58Check encoding using dart:convert interface
version: 2.0.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/dartcoin/base58check

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.2
